### ISSUE TITLE
not working on my server pls help

### ISSUE THREAD

**Issue by HeimTechniker** [XSilverSlayerX/ItemJoin#3]
I have installed the ItemJoin plugin on my Server and in the Serverlog file the plugin works! Ingame the Plugin is green, not red.   But no Items are in the Inventory. What can I do ?   my spawn world is the world: "Spawn".  For the files from plugin etc.  add me of skype:  "Heim Gaming"

**Comment by XSilverSlayerX** [comment]
1.) Do you have Multiverse 2.5 (BETA) installed? This exact file: http://dev.bukkit.org/bukkit-plugins/multiverse-core/files/28-2-5-b699-beta/

2.) Is there any error codes in console?
